print ("=============")
print ("BIODATA SAYA")
print ("=============")
print ("Nama : Zainal Abidin")
print ("Nama Pangilan : Nal/Gondrong")
print ("NIM : 312110105")
print ("Hobby : Hiking")
print ("Tempat tanggal lahir : Bogor, 22 Aprin 1999")
print ("Umur : 22th")
print ("Alamat : Kp.Pabuaran Kec.Cariu Ds.Cariu Kab.Bogor")
print ("Telepon :0821-2222-7691")